import { seedIds } from "./ids";

export const customerSeeds = [
  {
    id: seedIds.customers.apartments,
    organisationId: seedIds.organisation,
    displayName: "Alice Springs Apartments",
    email: "maintenance@asapartments.example",
    phone: "08 8950 1122",
    customerType: "real_estate" as const,
    billingAddress: "12 Todd Mall, Alice Springs NT 0870",
    invoiceTerms: "14 days from invoice date",
    communicationPreferences: "Email for approvals, SMS for access updates",
    propertyManagerDetails: "Property manager prefers grouped invoices by property.",
    internalNotes: "Property manager prefers grouped invoices by property.",
    portalEnabled: true,
  },
  {
    id: seedIds.customers.flynn,
    organisationId: seedIds.organisation,
    displayName: "Flynn Drive Residence",
    email: "flynn.family@example.com",
    phone: "0400 122 744",
    customerType: "residential" as const,
    billingAddress: "18 Flynn Drive, Alice Springs NT 0870",
    invoiceTerms: "Due on receipt",
    communicationPreferences: "SMS reminders and email reports",
    ownerDetails: "Primary contact: Mia Flynn",
    internalNotes: "Gate is usually unlocked on service mornings.",
    portalEnabled: true,
    portalUserId: seedIds.users.customerFlynn,
  },
  {
    id: seedIds.customers.resort,
    organisationId: seedIds.organisation,
    displayName: "Desert Springs Resort",
    email: "facilities@desertsprings.example",
    phone: "08 8951 8840",
    customerType: "commercial" as const,
    billingAddress: "90 Palm Circuit, Alice Springs NT 0870",
    invoiceTerms: "30 days from invoice date",
    communicationPreferences: "Email reports to facilities team",
    internalNotes: "Service outside peak guest hours where possible.",
    portalEnabled: false,
  },
  {
    id: seedIds.customers.eastside,
    organisationId: seedIds.organisation,
    displayName: "Eastside Family Pool",
    email: "eastside.pool@example.com",
    phone: "0412 882 019",
    customerType: "residential" as const,
    billingAddress: "4 Kurrajong Drive, East Side NT 0870",
    invoiceTerms: "7 days from invoice date",
    communicationPreferences: "SMS first, email invoices",
    internalNotes: "Customer asked to monitor pH drift over summer.",
    portalEnabled: true,
  },
];
