import { seedIds } from "./ids";

export const equipmentSeeds = [
  {
    id: seedIds.equipment.flynnPump,
    organisationId: seedIds.organisation,
    siteId: seedIds.sites.flynn,
    poolId: seedIds.pools.flynnMain,
    equipmentType: "Pump",
    brand: "AstralPool",
    model: "Viron P320",
    serialNumber: "FLYNN-PUMP-001",
    conditionNotes: "Operating normally.",
  },
  {
    id: seedIds.equipment.flynnChlorinator,
    organisationId: seedIds.organisation,
    siteId: seedIds.sites.flynn,
    poolId: seedIds.pools.flynnMain,
    equipmentType: "Chlorinator",
    brand: "Hayward",
    model: "AquaRite",
    serialNumber: "FLYNN-SALT-001",
    conditionNotes: "Output should be reviewed at next visit.",
    replacementRecommendation: "Monitor cell condition.",
  },
  {
    id: seedIds.equipment.gillenPump,
    organisationId: seedIds.organisation,
    siteId: seedIds.sites.gillen,
    poolId: seedIds.pools.gillenPlunge,
    equipmentType: "Pump",
    brand: "Davey",
    model: "PowerMaster",
    serialNumber: "GILLEN-PUMP-001",
    conditionNotes: "Bearing noise reported.",
  },
  {
    id: seedIds.equipment.gillenFilter,
    organisationId: seedIds.organisation,
    siteId: seedIds.sites.gillen,
    poolId: seedIds.pools.gillenPlunge,
    equipmentType: "Filter",
    brand: "Waterco",
    model: "Micron",
    serialNumber: "GILLEN-FILTER-001",
    conditionNotes: "Filter service due.",
  },
  {
    id: seedIds.equipment.resortHeater,
    organisationId: seedIds.organisation,
    siteId: seedIds.sites.resort,
    poolId: seedIds.pools.resortSpa,
    equipmentType: "Heater",
    brand: "Raypak",
    model: "Commercial gas heater",
    serialNumber: "RESORT-HEATER-001",
    conditionNotes: "Operating normally.",
  },
  {
    id: seedIds.equipment.resortFilter,
    organisationId: seedIds.organisation,
    siteId: seedIds.sites.resort,
    poolId: seedIds.pools.resortSpa,
    equipmentType: "Filter",
    brand: "Pentair",
    model: "Commercial cartridge",
    serialNumber: "RESORT-FILTER-001",
    conditionNotes: "Pressure remains within normal range.",
  },
  {
    id: seedIds.equipment.eastsidePump,
    organisationId: seedIds.organisation,
    siteId: seedIds.sites.eastside,
    poolId: seedIds.pools.eastsideMain,
    equipmentType: "Pump",
    brand: "AstralPool",
    model: "E-Series",
    serialNumber: "EASTSIDE-PUMP-001",
    conditionNotes: "Customer reports louder running after dust storms.",
  },
];
