import { seedIds } from "./ids";

export const poolSeeds = [
  {
    id: seedIds.pools.flynnMain,
    organisationId: seedIds.organisation,
    siteId: seedIds.sites.flynn,
    name: "Main family pool",
    volumeLitres: 52000,
    poolType: "In-ground concrete",
    surfaceType: "Pebblecrete",
    sanitiserType: "Salt chlorinator",
    environment: "Outdoor",
    normalChemicalBehaviour: "Leaves collect near the shallow-end skimmer after windy days.",
    targetRanges: { freeChlorine: "2-4 ppm", ph: "7.4-7.6", alkalinity: "80-120 ppm" },
    serviceNotes: "Leaves collect near the shallow-end skimmer after windy days.",
  },
  {
    id: seedIds.pools.gillenPlunge,
    organisationId: seedIds.organisation,
    siteId: seedIds.sites.gillen,
    name: "Rental plunge pool",
    volumeLitres: 18000,
    poolType: "Plunge pool",
    surfaceType: "Fibreglass",
    sanitiserType: "Mineral system",
    environment: "Outdoor",
    normalChemicalBehaviour: "Dust load can increase phosphate demand.",
    targetRanges: { freeChlorine: "2-4 ppm", ph: "7.2-7.6", salt: "3500-4500 ppm" },
    serviceNotes: "Tenant reports heavy dust after nearby landscaping work.",
  },
  {
    id: seedIds.pools.resortSpa,
    organisationId: seedIds.organisation,
    siteId: seedIds.sites.resort,
    name: "Commercial spa",
    volumeLitres: 9500,
    poolType: "Commercial spa",
    surfaceType: "Tiled",
    sanitiserType: "Liquid chlorine",
    environment: "Outdoor",
    heaterInformation: "Gas heater checked during early service windows.",
    spaInformation: "High bather load on weekends.",
    normalChemicalBehaviour: "Alkalinity needs close monitoring.",
    targetRanges: { freeChlorine: "3-5 ppm", ph: "7.4-7.6", alkalinity: "80-100 ppm" },
    serviceNotes: "High bather load on weekends. Check filter pressure every visit.",
  },
  {
    id: seedIds.pools.eastsideMain,
    organisationId: seedIds.organisation,
    siteId: seedIds.sites.eastside,
    name: "Eastside family pool",
    volumeLitres: 44000,
    poolType: "In-ground vinyl",
    surfaceType: "Vinyl liner",
    sanitiserType: "Salt chlorinator",
    environment: "Outdoor",
    normalChemicalBehaviour: "Recurring high pH.",
    targetRanges: { freeChlorine: "2-4 ppm", ph: "7.2-7.6", alkalinity: "80-120 ppm" },
    serviceNotes: "Recurring high pH. Check cell output and acid demand.",
  },
];
