import { seedIds } from "./ids";

export const siteSeeds = [
  {
    id: seedIds.sites.flynn,
    organisationId: seedIds.organisation,
    customerId: seedIds.customers.flynn,
    name: "Flynn Drive Residence",
    addressLine1: "18 Flynn Drive",
    suburb: "Alice Springs",
    state: "NT",
    postcode: "0870",
    gateCode: "No code",
    accessNotes: "Side gate on left of carport",
    accessWarning: "Gate latch sticks in hot weather",
    petWarnings: "Friendly dog may be in yard",
    tenantDetails: "Owner occupied",
    ownerAgentDetails: "Primary contact: Mia Flynn",
  },
  {
    id: seedIds.sites.gillen,
    organisationId: seedIds.organisation,
    customerId: seedIds.customers.apartments,
    name: "Gillen Rental",
    addressLine1: "7 Tmara Mara Circuit",
    suburb: "Gillen",
    state: "NT",
    postcode: "0870",
    gateCode: "4421",
    accessNotes: "Use rear laneway gate",
    accessWarning: "Confirm tenant access before arrival",
    petWarnings: "No pets listed",
    tenantDetails: "Tenant: R. Smith",
    ownerAgentDetails: "Agent: Alice Springs Apartments",
  },
  {
    id: seedIds.sites.larapinta,
    organisationId: seedIds.organisation,
    customerId: seedIds.customers.apartments,
    name: "Larapinta Townhouse",
    addressLine1: "22 Albrecht Drive",
    suburb: "Larapinta",
    state: "NT",
    postcode: "0870",
    gateCode: "Key safe 9037",
    accessNotes: "Key safe beside meter box",
    accessWarning: "Key safe code changes monthly",
    petWarnings: "Dog warning on file",
    tenantDetails: "Tenant details held by agent",
    ownerAgentDetails: "Agent: Alice Springs Apartments",
  },
  {
    id: seedIds.sites.resort,
    organisationId: seedIds.organisation,
    customerId: seedIds.customers.resort,
    name: "Desert Springs Resort",
    addressLine1: "90 Palm Circuit",
    suburb: "Desert Springs",
    state: "NT",
    postcode: "0870",
    gateCode: "Facilities access card",
    accessNotes: "Check in with facilities office",
    accessWarning: "Guest areas require hi-vis before 9 AM",
    petWarnings: "No pets",
    tenantDetails: "Commercial site",
    ownerAgentDetails: "Facilities manager: Dan Morris",
  },
  {
    id: seedIds.sites.eastside,
    organisationId: seedIds.organisation,
    customerId: seedIds.customers.eastside,
    name: "Eastside Family Pool",
    addressLine1: "4 Kurrajong Drive",
    suburb: "East Side",
    state: "NT",
    postcode: "0870",
    gateCode: "No code",
    accessNotes: "Front gate beside carport",
    accessWarning: "Call if gate is locked",
    petWarnings: "No pets listed",
    tenantDetails: "Owner occupied",
    ownerAgentDetails: "Primary contact: Eastside Family Pool",
  },
];
