ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "customer_id" uuid REFERENCES "customers"("id");
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "display_name" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "sku" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "supplier" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "purchase_date" date;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "warranty_period_number" integer;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "warranty_period_unit" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "manual_status" text NOT NULL DEFAULT 'Active';
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "record_type" text NOT NULL DEFAULT 'Existing equipment recorded';
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "price_sold_cents" integer;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "cost_price_cents" integer;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "labour_included" boolean NOT NULL DEFAULT false;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "linked_quote_id" uuid REFERENCES "quotes"("id");
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "linked_invoice_id" uuid REFERENCES "invoices"("id");
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "linked_job_id" uuid REFERENCES "jobs"("id");
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "installer_user_id" text REFERENCES "users"("id");
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "warranty_provider" text NOT NULL DEFAULT 'Unknown';
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "warranty_notes" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "warranty_claim_notes" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "serial_number_required" boolean NOT NULL DEFAULT false;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "internal_notes" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "customer_facing_notes" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "service_notes" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "future_maintenance_notes" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "evidence_checklist" jsonb;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "manual_customer_name" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "manual_customer_contact" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "manual_address" text;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now() NOT NULL;
