export const equipmentTypeOptions = [
  "Pump",
  "Variable speed pump",
  "Filter",
  "Sand filter",
  "Cartridge filter",
  "Glass media filter",
  "Chlorinator",
  "Salt chlorinator",
  "Mineral chlorinator",
  "Chlorine feeder",
  "Salt cell",
  "Heater",
  "Heat pump",
  "Gas heater",
  "Solar heating",
  "Robotic cleaner",
  "Suction cleaner",
  "Pressure cleaner",
  "Pool cleaner",
  "Automation/controller",
  "Chemical controller",
  "pH/ORP controller",
  "Dosing pump",
  "Pool light",
  "Transformer",
  "Valve/actuator",
  "Skimmer",
  "Return fitting",
  "Pool blanket/roller",
  "Water feature equipment",
  "Spa blower",
  "Other",
] as const;

export const equipmentBrandOptions = [
  "Madimack",
  "AstralPool",
  "Zodiac",
  "Baracuda",
  "MagnaPool",
  "Jandy",
  "Polaris",
  "Davey",
  "Waterco",
  "Aquaswim",
  "Baker Hydro",
  "Lacron",
  "Poppits",
  "Hayward",
  "Pentair",
  "Onga",
  "Sta-Rite",
  "Maytronics",
  "Dolphin",
  "Kreepy Krauly",
  "Daisy",
  "Spa Electrics",
  "Lincoln",
  "BWT",
  "Poolrite",
  "Pool Systems",
  "Aussie Gold",
  "Life",
  "PoolStyle",
  "Puraway",
  "SwimSafe",
  "SuperPro",
  "True Blue",
  "Emaux",
  "EvoHeat",
  "Naked Pools",
  "AquaQuip",
  "Chemigem",
  "Autochlor",
  "Chloromatic",
  "AIS",
  "Reltech",
  "Saltmate",
  "Sunbather",
  "ABGAL",
  "Noria",
  "PAL",
  "Speck",
  "Watermaid",
  "Pool Controls",
  "Pool Pro",
  "Other / Unknown",
] as const;

export const warrantyPeriodUnitOptions = ["months", "years"] as const;

export const recordTypeOptions = [
  "Sold only",
  "Installed only",
  "Sold and installed",
  "Existing equipment recorded",
  "Replaced equipment",
  "Warranty replacement",
] as const;

export const manualEquipmentStatusOptions = [
  "Active",
  "Monitor",
  "Service due",
  "Fault reported",
  "Replaced",
  "Removed",
  "Retired",
  "Unknown",
] as const;

export const warrantyProviderOptions = [
  "Manufacturer",
  "Supplier",
  "Outback Pool & Spa Services",
  "Unknown",
] as const;

export const evidenceCategoryOptions = [
  "Before installation",
  "After installation",
  "Serial number plate",
  "Model/specification plate",
  "Installed position",
  "Plumbing connection",
  "Electrical/control connection",
  "Old equipment removed",
  "Warranty card/manual",
  "Proof of purchase/receipt",
  "Compliance/safety evidence",
  "Other",
] as const;
